name: tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.5, 8.4, 8.3, 8.2]
        laravel: [^12.0, ^13.0]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: ^12.0
            testbench: ^10.0
          - laravel: ^13.0
            testbench: ^11.0
        exclude:
          - laravel: ^13.0
            php: 8.2

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Cache dependencies
        uses: actions/cache@v6
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-${{ hashFiles('composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: gd
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
